### PR TITLE
Update syntactical issues in readme

### PR DESCRIPTION
**Pull request by danieldelcore**
- Adds spaces before header text
- fixes indentation of css example

@davidchin 
@icatalina 
@supercrabtree

### CODE REVIEW

**Comment by supercrabtree** [comment]
Nice, LGTM 👍

**Comment by danieldelcore** [comment]
Thanks @supercrabtree!
I don't have write access to this! Can someone merge for me :P

**Comment by supercrabtree** [comment]
@PascalZajac ^

**Comment by danieldelcore** [comment]
help me haha! My intentions are good, i swear!

**Pull request merged**
